In [1]:
# 1mil is 1.6 km 
# 1 gallon is 3.7 km

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = sns.load_dataset('mpg')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [4]:
df.drop("name" , axis = 1 , inplace = True)

In [5]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa
...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa
394,44.0,4,97.0,52.0,2130,24.6,82,europe
395,32.0,4,135.0,84.0,2295,11.6,82,usa
396,28.0,4,120.0,79.0,2625,18.6,82,usa
397,31.0,4,119.0,82.0,2720,19.4,82,usa

In [6]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,18.0,8,307.0,130.0,3504,12.0,70,usa
1,15.0,8,350.0,165.0,3693,11.5,70,usa
2,18.0,8,318.0,150.0,3436,11.0,70,usa
3,16.0,8,304.0,150.0,3433,12.0,70,usa
4,17.0,8,302.0,140.0,3449,10.5,70,usa

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [8]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [9]:
# since we have not done outlier treatement , then better idea would be to replace the missing value with median 



df['horsepower'].median()

93.5

In [10]:
df['horsepower']=df['horsepower'].fillna(df['horsepower'].median())

In [11]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
dtypes: float64(4), int64(3), object(1)
memory usage: 25.0+ KB

In [13]:
df['origin'].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [14]:
# data encoding 

df['origin'] = df['origin'].map({"usa":1,"japan":2,"europe":3})

In [15]:
df['origin'] = df['origin'].astype(int)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int32
dtypes: float64(4), int32(1), int64(3)
memory usage: 23.4 KB

In [17]:
# separte x and y

In [18]:
x = df.drop('mpg', axis = 1)
y = df['mpg']

In [19]:
x

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
0,8,307.0,130.0,3504,12.0,70,1
1,8,350.0,165.0,3693,11.5,70,1
2,8,318.0,150.0,3436,11.0,70,1
3,8,304.0,150.0,3433,12.0,70,1
4,8,302.0,140.0,3449,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.0,2790,15.6,82,1
394,4,97.0,52.0,2130,24.6,82,3
395,4,135.0,84.0,2295,11.6,82,1
396,4,120.0,79.0,2625,18.6,82,1
397,4,119.0,82.0,2720,19.4,82,1

In [20]:
y

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [21]:
# train test split 

from sklearn.model_selection import train_test_split
x_train , x_test,y_train , y_test = train_test_split(x,y , test_size = 0.3 , random_state = 1)

In [22]:
x_train.shape

(278, 7)

In [23]:
y_train.shape

(278,)

In [24]:
x_test.shape

(120, 7)

# simple linear Regression

In [25]:
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()
regression_model

LinearRegression()

In [26]:
regression_model.fit(x_train , y_train)

LinearRegression()

In [27]:
regression_model.coef_

array([-0.31761423,  0.02623748, -0.01827076, -0.00748775,  0.05040673,
        0.84709514,  1.51909584])

In [28]:
for i , col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {regression_model.coef_[i]}")

The coefficient for cylinders is -0.3176142302799283
The coefficient for displacement is 0.026237482599078907
The coefficient for horsepower is -0.018270764913124578
The coefficient for weight is -0.007487750398361905
The coefficient for acceleration is 0.05040673461971364
The coefficient for model_year is 0.8470951427061364
The coefficient for origin is 1.5190958387975044

####  observation :
- coefficient are relatively smaller , if one independent variable chnage 
- there will be not much difference in prediction
- This is sometime called as smoother model
- these features might not be contributing in model training

In [29]:
from sklearn.metrics import r2_score

y_pred_linear = regression_model.predict(x_test)
r2_linear  = r2_score(y_test , y_pred_linear)
print(f"The R- square of linear regression {r2_linear}")

The R- square of linear regression 0.8348001123742285

# Regularised model 
- Ridge Regression

In [30]:
from sklearn.linear_model import Ridge

ridge_regression_model = Ridge(alpha = 0.1)
ridge_regression_model 
# in prarical implementation lambda is alpha

Ridge(alpha=0.1)

In [31]:
ridge_regression_model.fit(x_train , y_train)

Ridge(alpha=0.1)

In [32]:
for i , col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {ridge_regression_model.coef_[i]}")

The coefficient for cylinders is -0.31700321010063875
The coefficient for displacement is 0.02621324975798263
The coefficient for horsepower is -0.018263252481448757
The coefficient for weight is -0.007487326050213117
The coefficient for acceleration is 0.050368969474426185
The coefficient for model_year is 0.8470062938903149
The coefficient for origin is 1.5174528285653734

In [33]:
# for ridge regression model evaluation 

y_pred_ridge = ridge_regression_model.predict(x_test)
r2_ridge = r2_score(y_test , y_pred_ridge)
print(f"The R- square of ridge regression {r2_ridge}")

The R- square of ridge regression 0.834808488916836

In [34]:
# we dont see much variation in coeff of ridge regresion as compared to linear regression

# Lasso Regression

In [35]:
from sklearn.linear_model import Lasso

In [36]:
lasso_regression_model = Lasso()
lasso_regression_model

Lasso()

In [37]:
lasso_regression_model.fit(x_train , y_train)

Lasso()

In [38]:
for i , col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {lasso_regression_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.004712460689631323
The coefficient for horsepower is -0.010751274809550062
The coefficient for weight is -0.006879996579064627
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.7011781909435478
The coefficient for origin is 0.0

In [39]:
# three features coefficient is 0  , lasso helps in features selection

In [40]:
y_pred_lasso  = lasso_regression_model.predict(x_test)
r2_lasso = r2_score(y_test , y_pred_lasso)
print(f"The R- square of lasso regression {r2_lasso}")

The R- square of lasso regression 0.8293693600371324

# Elastic net

In [41]:
from sklearn.linear_model import ElasticNet
elastic_net_model = ElasticNet(alpha = 1 , l1_ratio=0.5)
elastic_net_model

ElasticNet(alpha=1)

In [42]:
elastic_net_model.fit(x_train , y_train)

ElasticNet(alpha=1)

In [43]:
for i , col_name in enumerate(x_train.columns):
    print(f"The coefficient for {col_name} is {elastic_net_model.coef_[i]}")

The coefficient for cylinders is -0.0
The coefficient for displacement is 0.0058888699536675535
The coefficient for horsepower is -0.012403874933570123
The coefficient for weight is -0.00693455051625763
The coefficient for acceleration is 0.0
The coefficient for model_year is 0.7133150744603872
The coefficient for origin is 0.0

In [44]:
y_pred_elastic_net  = elastic_net_model.predict(x_test)
r2_elastic_net = r2_score(y_test , y_pred_lasso)
print(f"The R- square of Elastic regression {r2_elastic_net}")

The R- square of Elastic regression 0.8293693600371324

# regularisation with cross validation

In [45]:
from sklearn.linear_model import LassoCV
lasso_cv = LassoCV(cv = 5 , verbose = 2)
lasso_cv

LassoCV(cv=5, verbose=2)

In [46]:
lasso_cv_model = lasso_cv.fit(x_train , y_train )
lasso_cv_model

Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100
Path: 000 out of 100
Path: 001 out of 100
Path: 002 out of 100
Path: 003 out of 100
Path: 004 out of 100
Path: 005 out of 100
Path: 006 out of 100
Path: 007 out of 100
Path: 008 out of 100
Path: 009 out of 100
Path: 010 out of 100
Path: 011 out of 100
Path: 012 out of 100
Path: 013 out of 100
Path: 014 out of 100
Path: 015 out of 100
Path: 016 out of 100
Path: 017 out of 100
Path: 018 out of 100
Path: 019 out of 100
Path: 020 out of 100
Path: 021 out of 100
Path: 022 out of 100
Path: 023 out of 100
Path: 024 out of 100
Path: 025 out of 100
Path: 026 out of 100
Path: 027 out of 100
Path: 028 out of 100
Path: 029 out of 100
Path: 030 out of 100
Path: 031 out of 100
Path: 032 out of 100
Path: 033 out of 100
Path: 034 out of 100
Path: 035 out of 100
Path: 036 out of 100
Path: 037 out of 100
Path: 038 out of 100
Path: 039 out of 100
Path: 040 out of 100
Path: 041 out of 100
Path: 042 out of 100
Path: 043 out of 100
Path: 044 out of 100
Path: 045 out of 100
Path: 046 out of 100
Path: 047 out of 100
Path: 048 out of 100
Path: 049 out of 100
Path: 050 out of 100
Path: 051 out of 100
Path: 052 out of 100
Path: 053 out of 100
Path: 054 out of 100
Path: 055 out of 100
Path: 056 out of 100
Path: 057 out of 100
Path: 058 out of 100
Path: 059 out of 100
Path: 060 out of 100
Path: 061 out of 100
Path: 062 out of 100
Path: 063 out of 100
Path: 064 out of 100
Path: 065 out of 100
Path: 066 out of 100
Path: 067 out of 100
Path: 068 out of 100
Path: 069 out of 100
Path: 070 out of 100
Path: 071 out of 100
Path: 072 out of 100
Path: 073 out of 100
Path: 074 out of 100
Path: 075 out of 100
Path: 076 out of 100
Path: 077 out of 100
Path: 078 out of 100
Path: 079 out of 100
Path: 080 out of 100
Path: 081 out of 100
Path: 082 out of 100
Path: 083 out of 100
Path: 084 out of 100
Path: 085 out of 100
Path: 086 out of 100
Path: 087 out of 100
Path: 088 out of 100
Path: 089 out of 100
Path: 090 out of 100
Path: 091 out of 100
Path: 092 out of 100
Path: 093 out of 100
Path: 094 out of 100
Path: 095 out of 100
Path: 096 out of 100
Path: 097 out of 100
Path: 098 out of 100
Path: 099 out of 100

LassoCV(cv=5, verbose=2)

In [47]:
y_pred = lasso_cv_model.predict(x_test)
score = r2_score(y_test , y_pred)
print(f"The R- square of Lasso CV {score}")

The R- square of Lasso CV 0.808280598384475

In [48]:
from sklearn.linear_model import RidgeCV
ridgecv = RidgeCV(cv = 5 )
ridgecv

RidgeCV(cv=5)

In [49]:
ridgecv.fit(x_train , y_train )

RidgeCV(cv=5)

In [50]:
y_pred = ridgecv.predict(x_test)
r2_score(y_test , y_pred)

0.8354145247502054

In [51]:
ridgecv.get_params()

{'alpha_per_target': False,
 'alphas': (0.1, 1.0, 10.0),
 'cv': 5,
 'fit_intercept': True,
 'gcv_mode': None,
 'scoring': None,
 'store_cv_results': None,
 'store_cv_values': 'deprecated'}

In [52]:
from sklearn.linear_model import ElasticNetCV
elastic_cv = ElasticNetCV(cv = 5)
elastic_cv

ElasticNetCV(cv=5)

In [53]:
elastic_cv .fit(x_train , y_train)

ElasticNetCV(cv=5)

In [54]:
y_pred= elastic_cv.predict(x_test)
r2_score(y_test , y_pred)

0.792863401804916

### 2.CV With Hyperparameter tuning

In [57]:
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV
from sklearn.linear_model import Lasso , Ridge

In [59]:
# define the model 
lasso = Lasso()
lasso

Lasso()

In [60]:
# grid search cv 
param_grid = {'alpha':[0.001 , 0.01 , 0.1 , 1 , 10 , 100]}
param_grid

{'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}

In [61]:
grid_search = GridSearchCV(estimator = lasso , param_grid = param_grid , cv = 5 , scoring = 'r2' , verbose = 2)

In [62]:
grid_search

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [63]:
grid_search.fit(x_train , y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [64]:
grid_search.best_params_

{'alpha': 0.1}

In [65]:
grid_search.best_params_['alpha']

0.1

In [66]:
grid_search.best_score_

0.7964209726696481

In [67]:
grid_search.best_estimator_

Lasso(alpha=0.1)

In [68]:
y_pred = grid_search.best_estimator_.predict(x_test)
r2_score(y_test , y_pred)

0.8345318641232303

In [73]:
lasso = Lasso()
param_distributions = {'alpha':[0.001 , 0.01 , 0.1 , 10 , 1, 100]}
random_search_lasso = RandomizedSearchCV(estimator = lasso , param_distributions = param_distributions,n_iter = 3,  cv = 5 , scoring = 'r2' , verbose = 2)
random_search_lasso

# due to n_iter parameter in each cross validation random 3 parameter are selected

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 10, 1,
                                                  100]},
                   scoring='r2', verbose=2)

In [74]:
random_search_lasso.fit(x_train , y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 10, 1,
                                                  100]},
                   scoring='r2', verbose=2)

In [75]:
random_search_lasso.fit(x_train , y_train)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s

RandomizedSearchCV(cv=5, estimator=Lasso(), n_iter=3,
                   param_distributions={'alpha': [0.001, 0.01, 0.1, 10, 1,
                                                  100]},
                   scoring='r2', verbose=2)

In [76]:
random_search_lasso.best_estimator_

Lasso(alpha=0.01)

In [77]:
random_search_lasso.best_score_

0.7944410612391778

In [78]:
y_pred = random_search_lasso.best_estimator_.predict(x_test)
r2_score(y_test , y_pred)

0.8348812953883182

In [79]:
# Ridge Grid Search Cv

ridge = Ridge()
param_grid = {'alpha':[0.001 , 0.01 , 0.1 , 1 , 10 , 100]}
ridge = GridSearchCV(estimator = ridge , param_grid = param_grid , cv = 5 , scoring = 'r2', verbose = 2)
ridge.fit(x_train , y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END ........................................alpha=0.001; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END .........................................alpha=0.01; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ............................................alpha=1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s
[CV] END ..........................................alpha=100; total time=   0.0s

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}, scoring='r2',
             verbose=2)

In [80]:
ridge.best_params_

{'alpha': 10}

In [81]:
ridge.best_estimator_

Ridge(alpha=10)

In [82]:
y_pred = ridge.best_estimator_.predict(x_test)
r2_score(y_test , y_pred)

0.8354145247502054

In [88]:
# Ridge Randomized search cv
ridge = Ridge()
param_distributions = {'alpha':[0.001 , 0.01 , 0.1 , 1 , 10 , 100]}
ridge = RandomizedSearchCV(estimator = ridge , param_distributions = param_distributions ,n_iter = 2, cv = 5 , scoring = 'r2', verbose = 2)
ridge.fit(x_train , y_train)
print(ridge.best_params_)
print(ridge.best_estimator_)
y_pred = ridge.best_estimator_.predict(x_test)
print(f"Rscore :{r2_score(y_test , y_pred)}")

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ..........................................alpha=0.1; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
[CV] END ...........................................alpha=10; total time=   0.0s
{'alpha': 10}
Ridge(alpha=10)
Rscore :0.8354145247502054

In [90]:
# Elastic net grid search cv
model = ElasticNet()
param_grid = {'alpha':[0.001 , 0.01 , 0.1 , 1 , 10 , 100] , 
                      'l1_ratio':[0.1 , 0.4,0.9]}
model = GridSearchCV(estimator = model , param_grid= param_grid , cv = 5 , scoring = 'r2', verbose = 2)
model.fit(x_train , y_train)
print(model.best_params_)
print(model.best_estimator_)
y_pred = model.best_estimator_.predict(x_test)
print(f"Rscore :{r2_score(y_test , y_pred)}")

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.1; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.4; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ..........................alpha=0.001, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.1; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.4; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ...........................alpha=0.01, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=0.1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.1; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.4; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END ..............................alpha=1, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.1; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.4; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
[CV] END ............................alpha=100, l1_ratio=0.9; total time=   0.0s
{'alpha': 0.1, 'l1_ratio': 0.9}
ElasticNet(alpha=0.1, l1_ratio=0.9)
Rscore :0.8345726087080976

In [93]:
# Elastic net randomized search cv
model = ElasticNet()
param_distributions = {'alpha':[0.001 , 0.01 , 0.1 , 1 , 10 , 100] , 
                      'l1_ratio':[0.1 , 0.4,0.9]}
model = RandomizedSearchCV(estimator = model , param_distributions = param_distributions , n_iter = 2, cv = 5 , scoring = 'r2', verbose = 2)
model.fit(x_train , y_train)
print(model.best_params_)
print(model.best_estimator_)
y_pred = model.best_estimator_.predict(x_test)
print(f"Rscore :{r2_score(y_test , y_pred)}")

Fitting 5 folds for each of 2 candidates, totalling 10 fits
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.1; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
[CV] END .............................alpha=10, l1_ratio=0.4; total time=   0.0s
{'l1_ratio': 0.1, 'alpha': 10}
ElasticNet(alpha=10, l1_ratio=0.1)
Rscore :0.8161415791745439